name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_macos:
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[ci skip test]') &&
      !contains(github.event.head_commit.message, '[ci skip test_macos]')
    runs-on: macos-26
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode 26.2
      run: sudo xcode-select -s /Applications/Xcode_26.2.app
    - name: Run tests
      run: swift test
